import { getChannelVideosPage, getAllChannelVideos, getVideoDurations } from './youtube.js';
import { getAudioUrl, downloadAudio, cleanupAudio } from './ytdlp.js';
import { transcribeUrl, transcribeFile } from './transcribe.js';
import { fetchCaptions, cleanupCaptions } from './captions.js';
import { analyseEpisode, analyseDimensions } from './analyse.js';
import { getChannel, upsertChannel, upsertEpisode, getEpisodeByVideoId, getUserSettings, savePost } from './store.js';
import { generatePosts } from './analyse.js';

// Per-user sync state — in-memory, survives navigation but not server restarts
const EMPTY_STATE = () => ({
  running: false,
  userId: null,
  channelId: null,
  channelName: null,
  currentVideo: null,
  progress: 0,
  total: 0,
  processed: 0,
  currentBatch: 0,
  totalBatches: 0,
  errors: [],
  lastSyncedAt: null,
});

const syncStates = new Map();

export function getSyncState(userId) {
  if (!syncStates.has(userId)) syncStates.set(userId, EMPTY_STATE());
  return syncStates.get(userId);
}

export const syncState = EMPTY_STATE();

async function processVideo(userId, video, channelId, channelName) {
  const state = getSyncState(userId);
  console.log(`[sync:${userId}] Processing: ${video.title}`);
  state.currentVideo = video.title;

  const existing = await getEpisodeByVideoId(userId, video.videoId, channelId);
  const isNew = !existing;
  if (existing?.transcript && existing?.summary) {
    console.log(`[sync:${userId}] Skipping (already done): ${video.title}`);
    state.processed++;
    state.progress = Math.round((state.processed / state.total) * 100);
    return existing;
  }

  let audioPath = null;
  try {
    let transcript;

    // Fetch YouTube captions and clean up with Claude
    console.log(`[sync:${userId}] Fetching captions for: ${video.videoId}`);
    const raw = await fetchCaptions(video.videoId);
    console.log(`[sync:${userId}] Cleaning up captions with Claude`);
    transcript = await cleanupCaptions(raw, video.title);
    console.log(`[sync:${userId}] Captions ready (${transcript.length} chars)`);

    const [analysis, dimensions] = await Promise.all([
      analyseEpisode(transcript, video.title),
      analyseDimensions(transcript, video.title),
    ]);

    const episode = {
      id: `yt-${video.videoId}`,
      videoId: video.videoId,
      channelId,
      channelName,
      title: video.title,
      show: channelName,
      publishedAt: video.publishedAt?.split('T')[0],
      duration: video.duration || 0,
      youtubeUrl: video.youtubeUrl,
      thumbnail: video.thumbnail,
      transcript,
      summary: analysis.summary,
      topics: analysis.topics,
      sentiment: analysis.sentiment,
      dimensions,
      viewCount: video.viewCount || 0,
      likeCount: video.likeCount || 0,
      commentCount: video.commentCount || 0,
      syncedAt: new Date().toISOString(),
    };

    await upsertEpisode(userId, episode);

    // Auto-repurpose: generate posts for brand-new episodes if setting is on
    if (isNew) {
      try {
        const settings = await getUserSettings(userId);
        if (settings.autoRepurpose) {
          console.log(`[sync:${userId}] Auto-generating posts for: ${episode.title}`);
          const posts = await generatePosts(episode, ['twitter', 'linkedin', 'instagram', 'newsletter']);
          for (const [platform, content] of Object.entries(posts)) {
            if (!content) continue;
            await savePost(userId, {
              id: `post-${episode.videoId}-${platform}-${Date.now()}`,
              episodeId: episode.id,
              episodeTitle: episode.title,
              platform,
              content,
              status: 'draft',
              autoGenerated: true,
            });
          }
          console.log(`[sync:${userId}] Auto-posts saved for: ${episode.title}`);
        }
      } catch (err) {
        console.error(`[sync:${userId}] Auto-repurpose failed for "${episode.title}":`, err.message);
      }
    }

    state.processed++;
    state.progress = Math.round((state.processed / state.total) * 100);
    return episode;
  } finally {
    if (audioPath) cleanupAudio(audioPath);
  }
}

export async function syncChannel({ userId, channelId, videoIds, maxVideos = 20, batchSize = 5, batchDelay = 3000 } = {}) {
  const state = getSyncState(userId);
  if (state.running) throw new Error('Sync already in progress for this user');

  const channel = await getChannel(userId, channelId);
  if (!channel?.id) throw new Error('Channel not found');

  Object.assign(state, {
    running: true, userId, channelId, channelName: channel.name,
    errors: [], processed: 0, progress: 0, currentBatch: 0, totalBatches: 0,
  });

  try {
    let videos;

    if (videoIds?.length > 0) {
      state.currentVideo = 'Fetching video list…';
      const allVideos = await getAllChannelVideos(channelId);
      const idSet = new Set(videoIds);
      videos = allVideos.filter(v => idSet.has(v.videoId));
    } else {
      const { videos: fetched } = await getChannelVideosPage(channelId, { pageSize: Math.min(maxVideos, 50) });
      videos = fetched.slice(0, maxVideos);
    }

    const ids = videos.map(v => v.videoId);
    const stats = await getVideoDurations(ids);
    videos.forEach(v => {
      const s = stats[v.videoId] || {};
      v.duration = s.duration || 0;
      v.viewCount = s.viewCount || 0;
      v.likeCount = s.likeCount || 0;
      v.commentCount = s.commentCount || 0;
    });

    state.total = videos.length;
    state.totalBatches = Math.ceil(videos.length / batchSize);

    for (let b = 0; b < state.totalBatches; b++) {
      state.currentBatch = b + 1;
      const batch = videos.slice(b * batchSize, (b + 1) * batchSize);
      for (const video of batch) {
        try {
          await processVideo(userId, video, channelId, channel.name);
        } catch (err) {
          console.error(`[sync:${userId}] Error on "${video.title}":`, err.message);
          state.errors.push({ videoId: video.videoId, title: video.title, error: err.message });
          state.processed++;
          state.progress = Math.round((state.processed / state.total) * 100);
        }
      }
      if (b < state.totalBatches - 1) await new Promise(r => setTimeout(r, batchDelay));
    }

    const lastSyncedAt = new Date().toISOString();
    await upsertChannel(userId, { ...channel, lastSyncedAt });
    state.lastSyncedAt = lastSyncedAt;
    console.log(`[sync:${userId}] Done. ${state.processed} processed, ${state.errors.length} errors.`);
  } finally {
    state.running = false;
    state.currentVideo = null;
    state.progress = 100;
  }
}
